# -*- coding: utf-8 -*-
"""
Section 3.2 — Stacking Ensemble with Bayesian Optimization (Optuna-TPE)
Fully aligned, runnable, and reviewer-friendly implementation.

What this script does (aligned with the Methods text):
1) Builds a stacking ensemble with three heterogeneous base learners:
   - XGBoost (tree boosting)
   - Random Forest (bagging of decision trees)
   - Multilayer Perceptron (neural network)
   and a Logistic Regression meta-learner.

2) Uses ONLY base-learner probability outputs as meta-learner inputs:
   - passthrough = False
   - stack_method = 'predict_proba'
   This matches: "probability outputs generated by each base learner were used
   as inputs to the meta-learner".

3) Jointly tunes hyperparameters of all learners via Bayesian search:
   - Optuna TPESampler (TPE is widely used as a Bayesian/TPE-based optimizer)
   - Objective: maximize 5-fold stratified cross-validation ROC-AUC
   - Includes pruning to speed up search

4) Adds six multiplicative interaction terms (exact combinations stated in Methods):
   slope–rainfall, lithology–fault distance, slope–river distance,
   NDVI–rainfall, slope–structure, and TWI–rainfall.

5) Prevents data leakage:
   - Train/test split first
   - StandardScaler is fit on TRAIN only, then applied to TEST

6) Exports multi-angle feature importance consistent with the Methods:
   - XGBoost gain importance
   - Random Forest MDI importance
   - MLP permutation importance (scoring = ROC-AUC)
   - Standardized LR coefficients (for meta-features, since passthrough=False)

Outputs (saved under CFG['out_dir']):
- best_params.json
- cv_auc.txt
- test_metrics.json
- xgb_gain.csv
- rf_mdi.csv
- mlp_permutation_auc.csv
- meta_lr_stdcoef.csv
- scaler.pkl
- stacking_model.pkl
"""

import os
import json
import warnings
import joblib
import numpy as np
import pandas as pd
import optuna

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score, average_precision_score, accuracy_score
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.inspection import permutation_importance
from xgboost import XGBClassifier

warnings.filterwarnings("ignore")


# --------------------------------------------------------------------------------------
# Configuration block (edit this part to match your local environment and column names)
# --------------------------------------------------------------------------------------
CFG = {
    # Input CSV file
    "data_path": r"C:\Users\31253\Desktop\数据汇总\绘图\数据汇总\集成学习DEM\训练集.csv",

    # Target column: binary label (0/1) recommended
    "target_col": "灾害类别",

    # Base predictors used in Methods 3.2 (11 factors)
    "base_features": [
        "DEM", "坡度", "剖面曲率", "平面曲率", "岩性",
        "TWI", "降雨", "NDVI", "距河流距离", "距断层距离", "斜坡结构"
    ],

    # Output folder for all artifacts
    "out_dir": r"C:\Users\31253\Desktop\数据汇总\绘图\数据汇总\集成学习DEM\模型_optuna_aligned",

    # Train/test split settings
    "test_size": 0.15,
    "random_state": 42,

    # Optuna settings (Bayesian/TPE optimization)
    "n_trials": 50,
    "timeout_sec": None,   # e.g., 3600 for 1 hour, or None for no limit

    # Cross-validation settings
    "n_splits_cv": 5,

    # Permutation importance settings
    "perm_repeats": 20,
}


# --------------------------------------------------------------------------------------
# Data utilities
# --------------------------------------------------------------------------------------
def safe_ffill(df: pd.DataFrame) -> pd.DataFrame:
    """
    Forward-fill missing values.

    Note:
    - This is kept to remain consistent with your prior workflow.
    - If you want a more conventional imputation (e.g., median for continuous features),
      replace this function accordingly and update your Methods text.
    """
    df = df.copy()
    df.ffill(inplace=True)
    return df


def build_interactions(X: pd.DataFrame) -> pd.DataFrame:
    """
    Create the 6 multiplicative interaction terms listed in Methods 3.2.

    Required interactions (Methods):
    - slope–rainfall
    - lithology–fault distance
    - slope–river distance
    - NDVI–rainfall
    - slope–structure
    - TWI–rainfall

    The column names are kept in Chinese for direct mapping to your dataset.
    You can rename them if you prefer, but keep combinations unchanged.
    """
    X = X.copy()

    X["坡度_降雨"]       = X["坡度"] * X["降雨"]            # slope–rainfall
    X["岩性_距断层"]     = X["岩性"] * X["距断层距离"]      # lithology–fault distance
    X["坡度_距河流"]     = X["坡度"] * X["距河流距离"]      # slope–river distance
    X["NDVI_降雨"]       = X["NDVI"] * X["降雨"]            # NDVI–rainfall
    X["坡度_斜坡结构"]   = X["坡度"] * X["斜坡结构"]        # slope–structure
    X["TWI_降雨"]        = X["TWI"] * X["降雨"]             # TWI–rainfall

    return X


# --------------------------------------------------------------------------------------
# Model construction (Optuna trial -> a complete stacking model)
# --------------------------------------------------------------------------------------
def make_models_from_trial(trial: optuna.trial.Trial, seed: int) -> StackingClassifier:
    """
    Sample hyperparameters within the EXACT ranges described in Methods 3.2
    and build a StackingClassifier.

    Methods-defined search ranges:
    XGBoost:
      - learning_rate: 0.01–0.3
      - max_depth: 3–10
      - n_estimators: 100–800
      - subsample: 0.5–1.0
      - (colsample_bytree kept at 0.5–1.0; commonly tuned)

    Random Forest:
      - n_estimators: 200–1000
      - max_depth: 5–20
      - max_features: sqrt or log2

    MLP:
      - hidden-layer configurations (sampled here as 2–4 layers, 64–512 each)
      - alpha (L2 regularization): 1e-4–1e-2
      - learning_rate_init: 0.0005–0.01

    Meta-learner (Logistic Regression):
      - C: 0.01–10 (log scale)

    Important alignment detail:
    - passthrough=False ensures meta-learner uses ONLY base probabilities,
      matching the Methods narrative.
    """
    # -------------------------
    # XGBoost hyperparameters
    # -------------------------
    xgb_params = {
        "n_estimators": trial.suggest_int("xgb_n_estimators", 100, 800),
        "max_depth": trial.suggest_int("xgb_max_depth", 3, 10),
        "learning_rate": trial.suggest_float("xgb_learning_rate", 0.01, 0.3),
        "subsample": trial.suggest_float("xgb_subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("xgb_colsample_bytree", 0.5, 1.0),
        # min_child_weight is not explicitly listed in your Methods ranges,
        # but it is a standard XGB control parameter. If you prefer strict parity,
        # you can remove it from both script and Methods.
        "min_child_weight": trial.suggest_int("xgb_min_child_weight", 1, 10),
        "random_state": seed,
        # Use single thread for more stable reproducibility across machines.
        "n_jobs": 1,
        "eval_metric": "logloss",
        "verbosity": 0,
    }

    # -------------------------
    # Random Forest hyperparameters
    # -------------------------
    rf_params = {
        "n_estimators": trial.suggest_int("rf_n_estimators", 200, 1000),
        "max_depth": trial.suggest_int("rf_max_depth", 5, 20),
        "max_features": trial.suggest_categorical("rf_max_features", ["sqrt", "log2"]),
        "random_state": seed,
        "n_jobs": 1,
    }

    # -------------------------
    # MLP hyperparameters
    # -------------------------
    # We sample a variable depth network (2–4 hidden layers).
    n_layers = trial.suggest_int("mlp_n_layers", 2, 4)
    layer_sizes = []
    for i in range(n_layers):
        layer_sizes.append(trial.suggest_int(f"mlp_h{i+1}", 64, 512, step=64))

    mlp_params = {
        "hidden_layer_sizes": tuple(layer_sizes),
        "activation": "tanh",
        "alpha": trial.suggest_float("mlp_alpha", 1e-4, 1e-2, log=True),
        "learning_rate_init": trial.suggest_float("mlp_learning_rate_init", 5e-4, 1e-2, log=True),
        "max_iter": 1000,
        "early_stopping": True,
        "random_state": seed,
    }

    # -------------------------
    # Meta-learner (Logistic Regression) hyperparameters
    # -------------------------
    meta_params = {
        "C": trial.suggest_float("meta_C", 0.01, 10.0, log=True),
        "max_iter": 1000,
        "random_state": seed,
        "solver": "lbfgs",
    }

    # Instantiate learners
    xgb = XGBClassifier(**xgb_params)
    rf = RandomForestClassifier(**rf_params)
    mlp = MLPClassifier(**mlp_params)
    meta = LogisticRegression(**meta_params)

    # Build stacking model
    stack = StackingClassifier(
        estimators=[("xgb", xgb), ("rf", rf), ("mlp", mlp)],
        final_estimator=meta,
        cv=StratifiedKFold(n_splits=CFG["n_splits_cv"], shuffle=True, random_state=seed),
        stack_method="predict_proba",
        passthrough=False,  # Critical: meta receives only base probabilities
        n_jobs=1
    )
    return stack


# --------------------------------------------------------------------------------------
# Optuna objective function
# --------------------------------------------------------------------------------------
def objective(trial: optuna.trial.Trial, X_train: np.ndarray, y_train: pd.Series, seed: int) -> float:
    """
    Objective function for Optuna:
    - Maximize mean ROC-AUC over 5-fold Stratified CV on the TRAIN set only.

    Why ROC-AUC?
    - This matches the Methods statement: "The objective function maximized cross-validation AUC."
    """
    cv = StratifiedKFold(n_splits=CFG["n_splits_cv"], shuffle=True, random_state=seed)
    aucs = []

    model = make_models_from_trial(trial, seed=seed)

    for fold, (tr_idx, va_idx) in enumerate(cv.split(X_train, y_train)):
        X_tr, X_va = X_train[tr_idx], X_train[va_idx]
        y_tr, y_va = y_train.iloc[tr_idx], y_train.iloc[va_idx]

        # Train on current fold
        model.fit(X_tr, y_tr)

        # Predict probabilities for positive class and compute fold AUC
        y_prob = model.predict_proba(X_va)[:, 1]
        fold_auc = roc_auc_score(y_va, y_prob)
        aucs.append(fold_auc)

        # Report to Optuna (enables pruning)
        trial.report(fold_auc, step=fold)
        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return float(np.mean(aucs))


# --------------------------------------------------------------------------------------
# Importance exporting (multi-angle interpretability, aligned with Methods)
# --------------------------------------------------------------------------------------
def export_importances(final_model: StackingClassifier,
                       X_train: np.ndarray, y_train: pd.Series,
                       X_test: np.ndarray, y_test: pd.Series,
                       feature_cols: list, out_dir: str) -> None:
    """
    Export the multi-angle importance measures described in Methods 3.2:

    (A) XGBoost gain importance
        - Extracted from XGB booster using importance_type='gain'
        - Output: xgb_gain.csv

    (B) Random Forest mean decrease in impurity (MDI)
        - Extracted via rf.feature_importances_
        - Output: rf_mdi.csv

    (C) MLP permutation importance
        - Computed on the TEST set using scoring='roc_auc'
        - Output: mlp_permutation_auc.csv
        Notes:
          * Permutation importance is computationally expensive.
          * Using ROC-AUC keeps evaluation consistent with the main objective metric.

    (D) Standardized regression coefficients from the meta-learner (Logistic Regression)
        - Because passthrough=False, LR is fit on "meta-features" only:
          [p_xgb, p_rf, p_mlp] = predicted probabilities of the positive class
        - We compute standardized coefficients:
            stdcoef_j = coef_j * std(meta_feature_j)
          which accounts for different scales in meta-features.
        - Output: meta_lr_stdcoef.csv

    Important clarification:
    - Standardized coefficients here refer to meta-feature space (base probabilities),
      not the original environmental predictors. This is correct given the Methods statement
      that meta-learner uses base probabilities as inputs.
    """
    os.makedirs(out_dir, exist_ok=True)

    # Access fitted base estimators and meta estimator
    xgb = final_model.named_estimators_["xgb"]
    rf  = final_model.named_estimators_["rf"]
    mlp = final_model.named_estimators_["mlp"]
    lr  = final_model.final_estimator_

    # -------------------------
    # (A) XGBoost gain
    # -------------------------
    booster = xgb.get_booster()
    gain_dict = booster.get_score(importance_type="gain")  # keys are 'f0', 'f1', ...

    rows = []
    for k, v in gain_dict.items():
        # Map 'f12' -> 12 -> feature_cols[12]
        try:
            idx = int(k[1:])
            fname = feature_cols[idx] if 0 <= idx < len(feature_cols) else k
        except Exception:
            fname = k
        rows.append((fname, float(v)))

    xgb_gain_df = (pd.DataFrame(rows, columns=["feature", "gain"])
                   .sort_values("gain", ascending=False)
                   .reset_index(drop=True))
    xgb_gain_df.to_csv(os.path.join(out_dir, "xgb_gain.csv"), index=False, encoding="utf-8-sig")

    # -------------------------
    # (B) Random Forest MDI
    # -------------------------
    rf_mdi_df = (pd.DataFrame({
        "feature": feature_cols,
        "mdi": rf.feature_importances_.astype(float)
    }).sort_values("mdi", ascending=False).reset_index(drop=True))
    rf_mdi_df.to_csv(os.path.join(out_dir, "rf_mdi.csv"), index=False, encoding="utf-8-sig")

    # -------------------------
    # (C) MLP permutation importance (ROC-AUC)
    # -------------------------
    perm = permutation_importance(
        mlp,
        X_test, y_test,
        scoring="roc_auc",
        n_repeats=CFG["perm_repeats"],
        random_state=CFG["random_state"],
        n_jobs=1
    )

    mlp_perm_df = (pd.DataFrame({
        "feature": feature_cols,
        "perm_auc_mean": perm.importances_mean.astype(float),
        "perm_auc_std": perm.importances_std.astype(float)
    }).sort_values("perm_auc_mean", ascending=False).reset_index(drop=True))
    mlp_perm_df.to_csv(os.path.join(out_dir, "mlp_permutation_auc.csv"), index=False, encoding="utf-8-sig")

    # -------------------------
    # (D) Meta LR standardized coefficients (meta-feature space)
    # -------------------------
    # StackingClassifier.transform(X) returns meta-features for the final estimator.
    # With stack_method='predict_proba' and binary classification:
    # it yields 3 columns (one per base learner), each the positive-class probability.
    meta_X_train = final_model.transform(X_train)  # shape: (n_samples, 3)

    meta_feature_names = ["p_xgb", "p_rf", "p_mlp"]
    coef = lr.coef_.ravel().astype(float)          # length should match meta features
    std = meta_X_train.std(axis=0).astype(float)   # standard deviation of each meta feature
    stdcoef = coef * std

    meta_df = (pd.DataFrame({
        "meta_feature": meta_feature_names[:len(stdcoef)],
        "coef": coef[:len(stdcoef)],
        "std_x": std[:len(stdcoef)],
        "stdcoef": stdcoef[:len(stdcoef)],
        "abs_stdcoef": np.abs(stdcoef[:len(stdcoef)])
    }).sort_values("abs_stdcoef", ascending=False).reset_index(drop=True))
    meta_df.to_csv(os.path.join(out_dir, "meta_lr_stdcoef.csv"), index=False, encoding="utf-8-sig")

    # Optional: print top items for quick sanity check
    print("\n=== Feature Importance Exports ===")
    print("[XGB gain] Top 10:\n", xgb_gain_df.head(10))
    print("\n[RF MDI] Top 10:\n", rf_mdi_df.head(10))
    print("\n[MLP Permutation (AUC)] Top 10:\n", mlp_perm_df.head(10))
    print("\n[Meta LR |stdcoef|] (meta-features):\n", meta_df)


# --------------------------------------------------------------------------------------
# Main execution
# --------------------------------------------------------------------------------------
def main():
    # Create output folder
    os.makedirs(CFG["out_dir"], exist_ok=True)

    # -------------------------
    # 1) Load data
    # -------------------------
    df = pd.read_csv(CFG["data_path"])
    df = safe_ffill(df)

    # -------------------------
    # 2) Select features and target
    # -------------------------
    X = df[CFG["base_features"]].copy()
    y = df[CFG["target_col"]].astype(int)

    # -------------------------
    # 3) Add interaction terms (6)
    # -------------------------
    X = build_interactions(X)
    feature_cols = list(X.columns)

    # -------------------------
    # 4) Split first, then scale (prevents leakage)
    # -------------------------
    X_train_raw, X_test_raw, y_train, y_test = train_test_split(
        X, y,
        test_size=CFG["test_size"],
        stratify=y,
        random_state=CFG["random_state"]
    )

    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train_raw)  # fit ONLY on train
    X_test = scaler.transform(X_test_raw)

    # -------------------------
    # 5) Optuna Bayesian/TPE optimization to maximize CV ROC-AUC
    # -------------------------
    sampler = optuna.samplers.TPESampler(seed=CFG["random_state"])
    pruner = optuna.pruners.MedianPruner(n_startup_trials=10, n_warmup_steps=1)

    study = optuna.create_study(direction="maximize", sampler=sampler, pruner=pruner)

    study.optimize(
        lambda t: objective(t, X_train, y_train, seed=CFG["random_state"]),
        n_trials=CFG["n_trials"],
        timeout=CFG["timeout_sec"]
    )

    best_trial = study.best_trial
    best_auc = float(best_trial.value)
    best_params = best_trial.params

    # Persist best parameters and best CV score
    with open(os.path.join(CFG["out_dir"], "best_params.json"), "w", encoding="utf-8") as f:
        json.dump(best_params, f, ensure_ascii=False, indent=2)

    with open(os.path.join(CFG["out_dir"], "cv_auc.txt"), "w", encoding="utf-8") as f:
        f.write(f"Best mean CV AUC (n_splits={CFG['n_splits_cv']}): {best_auc:.6f}\n")

    print("=== Optuna Best Trial ===")
    print("Best mean CV AUC:", best_auc)
    print("Best params:", best_params)

    # -------------------------
    # 6) Rebuild and fit the final model using best hyperparameters
    # -------------------------
    seed = CFG["random_state"]

    xgb_final = XGBClassifier(
        n_estimators=best_params["xgb_n_estimators"],
        max_depth=best_params["xgb_max_depth"],
        learning_rate=best_params["xgb_learning_rate"],
        subsample=best_params["xgb_subsample"],
        colsample_bytree=best_params["xgb_colsample_bytree"],
        min_child_weight=best_params["xgb_min_child_weight"],
        random_state=seed,
        n_jobs=1,
        eval_metric="logloss",
        verbosity=0,
    )

    rf_final = RandomForestClassifier(
        n_estimators=best_params["rf_n_estimators"],
        max_depth=best_params["rf_max_depth"],
        max_features=best_params["rf_max_features"],
        random_state=seed,
        n_jobs=1,
    )

    n_layers = best_params["mlp_n_layers"]
    layers = [best_params[f"mlp_h{i+1}"] for i in range(n_layers)]
    mlp_final = MLPClassifier(
        hidden_layer_sizes=tuple(layers),
        activation="tanh",
        alpha=best_params["mlp_alpha"],
        learning_rate_init=best_params["mlp_learning_rate_init"],
        max_iter=1000,
        early_stopping=True,
        random_state=seed,
    )

    meta_final = LogisticRegression(
        C=best_params["meta_C"],
        max_iter=1000,
        random_state=seed,
        solver="lbfgs",
    )

    final_model = StackingClassifier(
        estimators=[("xgb", xgb_final), ("rf", rf_final), ("mlp", mlp_final)],
        final_estimator=meta_final,
        cv=StratifiedKFold(n_splits=CFG["n_splits_cv"], shuffle=True, random_state=seed),
        stack_method="predict_proba",
        passthrough=False,   # aligned with Methods
        n_jobs=1
    )

    final_model.fit(X_train, y_train)

    # -------------------------
    # 7) Evaluate on the held-out test set
    # -------------------------
    y_prob_test = final_model.predict_proba(X_test)[:, 1]

    # For accuracy we threshold at 0.5 (optional; AUC/AP are threshold-free)
    y_pred_test = (y_prob_test >= 0.5).astype(int)

    test_auc = float(roc_auc_score(y_test, y_prob_test))
    test_ap = float(average_precision_score(y_test, y_prob_test))
    test_acc = float(accuracy_score(y_test, y_pred_test))

    metrics = {
        "test_auc": test_auc,
        "test_pr_auc_ap": test_ap,
        "test_accuracy@0.5": test_acc,
        "n_train": int(len(y_train)),
        "n_test": int(len(y_test)),
        "n_features_after_interactions": int(X_train.shape[1]),
        "feature_names": feature_cols
    }

    with open(os.path.join(CFG["out_dir"], "test_metrics.json"), "w", encoding="utf-8") as f:
        json.dump(metrics, f, ensure_ascii=False, indent=2)

    print("\n=== Test Metrics ===")
    print("Test AUC:", test_auc)
    print("Test PR-AUC (AP):", test_ap)
    print("Test Accuracy@0.5:", test_acc)

    # -------------------------
    # 8) Export multi-angle importance measures (aligned with Methods narrative)
    # -------------------------
    export_importances(
        final_model=final_model,
        X_train=X_train, y_train=y_train,
        X_test=X_test, y_test=y_test,
        feature_cols=feature_cols,
        out_dir=CFG["out_dir"]
    )

    # -------------------------
    # 9) Save scaler and final stacking model for reproducibility
    # -------------------------
    joblib.dump(scaler, os.path.join(CFG["out_dir"], "scaler.pkl"))
    joblib.dump(final_model, os.path.join(CFG["out_dir"], "stacking_model.pkl"))

    print("\n✅ Saved artifacts to:", CFG["out_dir"])
    print(" - best_params.json")
    print(" - cv_auc.txt")
    print(" - test_metrics.json")
    print(" - xgb_gain.csv")
    print(" - rf_mdi.csv")
    print(" - mlp_permutation_auc.csv")
    print(" - meta_lr_stdcoef.csv")
    print(" - scaler.pkl")
    print(" - stacking_model.pkl")


if __name__ == "__main__":
    main()